global :
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus' #setup cadvisor
    static_configs:
      - targets: ['localhost:9090']

  # - job_name: cadvisor #setup cadvisor
  #   scrap_interval: 5s
  #   static_configs
  #     - targets; ['cadvisor:8080'] 